INSERT INTO CATEGORY (description) VALUES('American');
INSERT INTO CATEGORY (description) VALUES('Italian');
INSERT INTO CATEGORY (description) VALUES('Mexican');
INSERT INTO CATEGORY (description) VALUES('Fast Food');
INSERT INTO UNIT_OF_MEASURE(description) VALUES('teaspoon');
INSERT INTO UNIT_OF_MEASURE(description) VALUES('tablespoon');
INSERT INTO UNIT_OF_MEASURE(description) VALUES('cup');
INSERT INTO UNIT_OF_MEASURE(description) VALUES('pinche');
INSERT INTO UNIT_OF_MEASURE(description) VALUES('qunce');
INSERT INTO UNIT_OF_MEASURE(description) VALUES('unit');
